### ISSUE TITLE
I am not able to find unlabeled/test set mode in the explorer

### ISSUE THREAD

**Issue by petrjirasek** [fracpete/collective-classification-weka-package#1]
Hello,

I have just updated the package in my weka 3.7.12 and I am not able the new function mentioned in the release:
"Explorer panel now offers loading of unlabeled/test set in Unlabeled/test set mode"

![weka](https://cloud.githubusercontent.com/assets/888765/6337461/26981a80-bbaa-11e4-9a52-ba9cd7c8cd61.png)

Could you please help me where to find the new feature and how to use it?

Thank you very much!

Cheers,
Petr

**Comment by fracpete** [comment]
Maybe the updating didn't quite work... Here are my steps:
- download the latest release (at the time of writing <a href="https://github.com/fracpete/collective-classification-weka-package/releases/download/v2015.1.13/collective-classification-2015.1.13.zip">2015.1.13</a>)
- remove the existing collective-classification package (I simply removed the `$HOME/wekafiles/packages/collective-classification` directory)
- fire up Weka and open the Package manager
- install the new ZIP file that you downloaded
- restart Weka and open the Explorer

This is what the Explorer then looks like:

![collective_unlabeled_test_set](https://cloud.githubusercontent.com/assets/1026180/6340626/02f24d2c-bc26-11e4-92ee-cc38de28e3e7.png)

**Comment by petrjirasek** [comment]
@fracpete Can I ask you about the settings? I don't want to open a new issue. Thank you.

I am wondering how to set train, unlabeled and test set correctly. For instance, I have a dataset of 300 instances and I would like to test how good are in my case some collective classifiers.

I have created labeled train set 60 instances, 240 unlabeled instances as unlabeled set and the same 240 instances as test set, but the weka returns alert Attributes differ in attribute 2. Different number of labels 0 != 2 when I set it.

So, it means that unlabeled set must have labeled instances which are during building a training model ignored? In my case, the unlabeled test and test set will be probably the same, right?

Thank you for your help!
Petr

**Comment by fracpete** [comment]
I presume that you're using ARFF files. All your files, train/unlabeled/test, must have exactly the same structure (same attribute names, types, order of labels). Just make sure that your ARFF header for the unlabeled dataset also lists the 2 labels that your test set has. But you don't need to have labels in the unlabeled dataset, simply use the question mark for denoting a missing value instead. Yes, during build time any class labels from the unlabeled dataset get ignored. This allows you to use a test set also as unlabeled dataset.

**Comment by petrjirasek** [comment]
Thank you. It really helps. Sorry for interrupting but I would like to ask you one more question. I have tried the output option and set saver to CSV and set a output file file located in Desktop folder. But the saver after evaluating does not save anything. It's really weird. But uutput in classify tab for classifiers works well. Thank you,

**Comment by fracpete** [comment]
That was a nice bug. It worked for cross-validation, but not for the other test modes. I've fixed that and made a new released available:
https://github.com/fracpete/collective-classification-weka-package/releases/tag/v2015.2.27
Thanks for reporting the bug!

**Comment by petrjirasek** [comment]
Thanks for fast fix. I have just tried it and there is some problem in evaluation but it can be my mistake. I have created train set, unlabeled set and test set and try to evaluate it. But weka returns an error during processing - Problem evaluating - Cannot find instance (you can see it in the screen).
![weka screen](https://cloud.githubusercontent.com/assets/888765/6450756/5bbb6b1a-c12a-11e4-83b4-b3bb70940002.png)
I have uploaded my sets to dropbox here:
https://www.dropbox.com/sh/5afxvdtltkb8brc/AADN__F4ZCMpCDol_Dd8WqNFa?dl=0

I have checked count of attrbutes and other things and it's the same in all sets. I used FilteredCollectiveClassifier, where classifier is set to NaivebayesMultinomial in YATSI and filter is set to Remove -R first
Class is assigned to _class_ attribute.

Thank you for your help. You are wonderful.

**Comment by fracpete** [comment]
That was a limitation of some of the algorithms, that an identical (unlabeled) instance has to be present. Please note, that no development on the algorithms has happened in the last 7 years, I only made the existing code available as Weka package. Please submit a new issue with this information. I may have time to look into that - however, this is a very low-priority bug issue for me.

**Comment by petrjirasek** [comment]
SOrry, I don't completely understand: What does it means? "That was a limitation of some of the algorithms, that an identical (unlabeled) instance has to be present."
It means that every instance in unlabeled set has to be in test set?

Thank you for your answer.

**Comment by fracpete** [comment]
Yes.

**Comment by petrjirasek** [comment]
Ok, thanks!
