### ISSUE TITLE
I am not able to load the package in the weka.

### ISSUE THREAD

**Issue by PavlaU** [fracpete/collective-classification-weka-package#2]
Hello,
I am trying to load your collective-classification package in weka. I tried weka versions from 3.7.11 to 3.7.13. Package manger says "Package installed successfully", but it does not show the package under Installed and the weka Explorer does not have the collective sheet. I have OS X Yosemite.

Do you have a clue where may be the problem?

Thanks.
Pavla

**Comment by fracpete** [comment]
_Unofficial_ packages never show up in the package manager, unfortunately.
What version of the package did you try to install? Also, did you get any exceptions in the terminal when starting up Weka?
I just tried release 2015.2.27 in conjunction with 3.7.12  on my Linux machine (Linux Mint 17 Qiana, 64bit) and it works fine. Here are my steps:
- downloaded the [2015.2.27 release](https://github.com/fracpete/collective-classification-weka-package/releases/download/v2015.2.27/collective-classification-2015.2.27.zip)
- renamed `$HOME/wekafiles` to `$HOME/wekafiles.old` to ensure that that there is no interference from other already installed packages
- started up Weka 3.7.12 using `java -jar weka.jar`
- installed the package archive through the package manager
- restarted Weka and the Explorer showed the _Collective_ tab

**Comment by PavlaU** [comment]
Thanks for a quick reply. I have followed your approach with the same release of weka and collective package, but the result is still the same - no Collective tab. However, I managed to install the package on a computer that runs windows. It even shows the package under Installed in the package manager. Still, I would like to have it on my Mac. There must be a problem somewhere in my computer. Do you have some suggestions what to try?

**Comment by fracpete** [comment]
Unfortunately, I don't have a Mac. Do you start Weka from the terminal? Was there any error output? What version of Java do you use?

**Comment by PavlaU** [comment]
I tried to start from terminal as well. I updated my java to version 1.8.0_60 and tried the installation again. The problem persists. The problem must be somewhere in my mac, I will try to find someone with mac. Thanks for your help.

**Comment by fracpete** [comment]
What output did you have in the terminal when starting Weka?

**Comment by PavlaU** [comment]
Trying to install a file handler for Mac...

Than appears the GUI Chooser.

**Comment by fracpete** [comment]
OK. When you check the `$HOME/wekafiles/packages` directory. Do you see a `collective-classification` directory?

**Comment by PavlaU** [comment]
Yes I do.

**Comment by fracpete** [comment]
Hmm... Just grasping at straws here: Do you have a custom CLASSPATH environment variable set that might interfere with WEKA?
You can check this by running the following command in the terminal:
`echo $CLASSPATH`
If there is no output, then I don't see any reason why it shouldn't work. However, if you do have a custom classpath set, you could try unsetting it first before starting WEKA:
`set CLASSPATH=`

**Comment by PavlaU** [comment]
The command returns an empty row, the classpath is ok.

**Comment by fracpete** [comment]
OK, here's one more thing that I can think of. Remove the `$HOME/wekafiles/weka.log` log file and start up WEKA again from the terminal using `java -jar weka.jar`. What is the content of the newly created `weka.log` file?

**Comment by PavlaU** [comment]
2015-10-02 23:08:33 weka.gui.GUIChooser main
INFO: Logging started
2015-10-02 23:08:35 weka.gui.GenericObjectEditor registerEditors
INFO: ---Registering Weka Editors---
2015-10-02 23:08:35 weka.gui.GenericObjectEditor registerEditor
WARNING: Problem registering ShowGlobalInfoToolTip/true: java.lang.ClassNotFoundException: ShowGlobalInfoToolTip
2015-10-02 23:08:35 weka.experiment.DatabaseUtils initialize
WARNING: Trying to add database driver (JDBC): jdbc.idbDriver - Warning, not in CLASSPATH?
2015-10-02 23:08:35 weka.gui.beans.BeansProperties loadProperties
INFO: [KnowledgeFlow] Loading properties and plugins...
2015-10-02 23:08:35 weka.gui.beans.KnowledgeFlowApp init
INFO: [KnowledgeFlow] Initializing KF...

**Comment by fracpete** [comment]
Nothing unusual there. Sorry, but I can't help you there any further. Your best bet is to ask on the Weka mailing list (http://www.cs.waikato.ac.nz/ml/weka/help.html) whether anyone has experienced a similar problem with an unofficial package on Mac OSX. For reference, you should also link to this issue here, so that people can see what has been tried already.

**Comment by PavlaU** [comment]
Thanks a lot for your effort.

**Comment by katehara** [comment]
Hi,
I am facing the same problem in Linux. Did you find a solution?

**Comment by fracpete** [comment]
What version of Weka do you use?

**Comment by fracpete** [comment]
closed due to inactivity
