### ISSUE TITLE
Predictions for unlabeled data

### ISSUE THREAD

**Issue by PavlaU** [fracpete/collective-classification-weka-package#3]
Hi,
is it possible to output YATSI predictions for unlabeled data? 
Thanks,
P.

**Comment by fracpete** [comment]
Yes, you can. In the _Collective_ tab in the Explorer, simply choose another output method than `Null`, e.g., `PlainText` or `CSV`. You can also specify a file to output the results to.
Predictions (_actual vs predicted_) are output for the available test set, which is automatically generated in case of _cross-validation_ and _random split_, explicitly provided in case of _Unlabeled/test set_.
If you want to output the predictions for the _unlabeled_ dataset, then you have to select _Unlabeled/test set_ and supply the unlabeled dataset also as _test_ set.

**Comment by PavlaU** [comment]
I am using Unlabeled/Test set option and csv output. However, the output only includes instances from the test set.

**Comment by fracpete** [comment]
That's why I said that you have to supply the _unlabeled_ dataset also as _test set_.

**Comment by PavlaU** [comment]
I supply both.

**Comment by fracpete** [comment]
Like I said earlier, if you want to output predictions for the _unlabeled_ dataset, you need to supply this dataset as _unlabeled_ **and** _test_ set. Here is an example CSV output obtained from using the UCI dataset _vote_:

```
inst#,actual,predicted,error,prediction
1,1:?,2:republican,,1
2,1:?,2:republican,,1
3,1:?,1:democrat,,1
4,1:?,1:democrat,,0.943
5,1:?,1:democrat,,1
6,1:?,1:democrat,,0.667
```

As you can see, the question mark denotes the missing label (_actual_) and next to it the _predicted_ label.

**Comment by PavlaU** [comment]
Got it, finally. Thanks a lot.
