### ISSUE TITLE
Project is missing required library: 'lib/packageManager.jar'

### ISSUE THREAD

**Issue by saharjoundi** [fracpete/collective-classification-weka-package#4]
Hello, I have just download the jar file, i import it in my eclipse however i have this error !! where can I find packageManager.jar?

**Comment by fracpete** [comment]
Import the project as Maven project instead, that should pull in all the correct libraries. Please note, I haven't tested the project with 3.8.x or 3.9.x yet.

**Comment by fracpete** [comment]
closed due to inactivity
